### ISSUE TITLE
Allow customization of webpack config when building ComponentPlayground

### ISSUE THREAD

**Issue by skidding** [skidding/cosmos#118]

**Comment by w0rm** [comment]
I'd like to put this project into use, but this issue is a must to have for me and I am willing to contribute.

Do you have any idea of how this should be implemented?

**Comment by skidding** [comment]
> Do you have any idea of how this should be implemented?

Let's start by figuring out what part of the webpack config you need to customize.

**Comment by w0rm** [comment]
Right now I have hacked up a simple solution.

I modified cosmos to accept config-path, then added this to webpack.config.js:

```javascript
if (argv.configPath) {
    config = require(resolvePath(argv.configPath))(config);
}
module.exports = config;
```

Then I have created my `cosmos.config.js`

```javascript
module.exports = function (config) {
    config.module.loaders = [
        {
            loaders: ['style', 'css', 'postcss'],
            test: /\.css$/
        },
        {
            exclude: /node_modules/,
            loaders: ['react-hot', 'babel'],
            test: /\.jsx?$/
        }
    ];
    config.postcss = require('./lib/postcss').processors;
    return config;
};
```

To start cosmos I use this command `component-playground --config-path cosmos.config.js`

**Comment by w0rm** [comment]
So I basically needed to override css loader and add config entry for postcss. But I might need more in the future, so I kinda like to have karma approach of being able to override default settings if needed.

**Comment by skidding** [comment]
> so I kinda like to have karma approach of being able to override default settings if needed.

You're right, all webpack arguments should be customizable.

I was thinking of having something like an optional `component-playground.config.js` in the project root, where you run `node_modules/.bin/component-playground`

And that config should extend the [built-in webpack config](https://github.com/skidding/cosmos/blob/master/component-playground/webpack.config.js#L14-L55). One question I faced so far: should it be shallow or deep extending? For `output.` you want it deep for sure, but not sure about the other keys where you'd rather reset the default value than extend it.

Also, the webpack config should be only a key inside `component-playground.config.js`, because you might want to customize other stuff as well, like the options for [ReactQueryStringRouter](https://github.com/skidding/react-querystring-router). E.g.

```js
// component-playground.config.js
{
  router: {
    defaultProps: {
      // ...
    },
  },
  webpack: {
    loaders: [
      // ...
    ]
  }
}
```

**Comment by w0rm** [comment]
What about having a function for each config section, that gets original config and returns modified, e.g. 

```javascript
// component-playground.config.js
module.exports = {
    webpack: function (config) {
        // modify and 
        return config
    },
    router: function (config) {
        // modify and 
        return config
    }
}
```

**Comment by skidding** [comment]
> What about having a function for each config section, that gets original config and returns modified, e.g.

Nice!

**Comment by w0rm** [comment]
Great, will make a pull request for this.
