### ISSUE TITLE
Have you considered to use smart-css instead of CSS/LESS files?

### ISSUE THREAD

**Issue by totty90** [skidding/cosmos#128]
In this way you have 100% encapsuled components (CSS+HTML+JS in a single JS file). Take a look at this lib here: https://github.com/hackhat/smart-css

**Comment by skidding** [comment]
As long as your components are encapsulated, you're free to use whatever you want for styles. If you have the time to try out Cosmos with components that use smart-css it'd be pretty cool to confirm.

I think the styles part from the README requirements is a bit confusing.

> which means you need to be using style-loader.

should be:

> which means you **probably** need to be using style-loader.

**Comment by gaearon** [comment]
I like that style-loader already has a built-in support for hot reloading.

**Comment by totty90** [comment]
@skidding Ok, thanks (:
@gaearon I didn't used hot reloading yet, but it's on my list.

**Comment by skidding** [comment]
Closing this as smart-css is outside the scope of Cosmos.
