### ISSUE TITLE
Introduce a way to compose components

### ISSUE THREAD

**Issue by w0rm** [skidding/cosmos#130]
To test some components, e.g. grid, it is necessary to be able to test their composition,
the code below worked for me for the 1st time, but not after I kicked in the editor. 

I understand that there is a limitation in the current implementation, but are there any plans or ideas of supporting this? 

```javascript
// fixtures/row/row/default.js
var React = require('react');
var Cell = require('../../../components/row/cell.jsx');

module.exports = {
    children: [
        React.createElement(Cell, {
            children: 'Col 1 Text',
            key: 'col1'
        }),
        React.createElement(Cell, {
            children: 'Col 2 Text',
            key: 'col2'
        }),
        React.createElement(Cell, {
            children: 'Col 3 Text',
            key: 'col3'
        })
    ]
};
```

**Comment by skidding** [comment]
> I understand that there is a limitation in the current implementation, but are there any plans or ideas of supporting this?

Positive.

The problem stems from they way the parsed fixture editor content extends the original fixture and the way unserializable fields are handled. I have a detailed plan for how to fix this, but it will take a couple of more days to get to it. I'll try to create a test very similar to your example to make sure it covers it.

**Comment by w0rm** [comment]
@skidding feel free to break my example, I can rewrite the stuff I'm working on.

**Comment by skidding** [comment]
@w0rm do you know of a way to determine weather or not a JS object is serializable?

`JSON.parse(JSON.stringify(obj))` is not reliable. E.g.

```js
var children = [
  React.createElement('span', {
    children: 'test child'
  })
];

// deep strict comparison
_.isEqual(children, JSON.parse(JSON.stringify(children)));
// return true
```

Of course they are not equal, the serialized/deserialized object doesn't have any inherited prototype...
