### ISSUE TITLE
Enable source maps by default

### ISSUE THREAD

**Issue by w0rm** [skidding/cosmos#131]
This is as easy as setting `devtool: 'eval'` in webpack config. I'm not sure if its possible to hide cosmos internals from being shown in the dev tools, for this I have asked a [question on stackoverflow](http://stackoverflow.com/questions/30476045/is-it-possible-to-disable-source-maps-for-certain-files-in-webpack).

**Comment by skidding** [comment]
Low priority now that you can [customize the webpack config](https://github.com/skidding/cosmos/pull/132). Let's see if others request for this default as well.

**Comment by skidding** [comment]
Cosmos is now a [boilerplate](https://github.com/skidding/cosmos/tree/master/webpack-boilerplate/react-0.13). The webpack config is now part of your project.
