### ISSUE TITLE
Hanging on `sass-loader`

### ISSUE THREAD

**Issue by ksmth** [skidding/cosmos#135]
I'm trying to overload the loaders as follows:
```
module.exports.webpack = function (webpackConfig) {
  webpackConfig.module.loaders = [
    {
      test   : /\.scss$/,
      loader : 'style!css?module&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass'
    },
    {
      test    : /\.jsx?$/,
      loaders : [ 'react-hot', 'babel?stage=0&optional=runtime' ],
      exclude : /node_modules/
    },
    {
      test   : /\.jpe?g$|\.gif$|\.png$|\.svg$|\.eot$|\.woff$|\.woff2$|\.ttf$/,
      loader : 'file'
    },
    { test: /\.css$/,  loader: 'style-loader!css-loader' },
    { test: /\.less$/, loader: 'style-loader!css-loader!less-loader' }
  ];

  webpackConfig.postcss = [
    require('autoprefixer-core')
  ];
  
  return webpackConfig;
};
```

When I comment out the `scss` loader part, it compiles, but will complain about `import styles from './stuff.scss';` statements or rather the contents of the file needing their own loader.

I tried setting the `resolveLoader.root` to my own `node_modules` folder, tried installing the loaders inside `node_modules/cosmos-js`, but nothing worked, it's hanging in an infinite loop somehow.

*Edit*

Reducing this further to:
```
module.exports.webpack = function (webpackConfig) {
  webpackConfig.module.loaders.push({
    test   : /\.scss$/,
    loader : 'style!css!sass'
  });

  return webpackConfig;
};
```

**Comment by skidding** [comment]
> Reducing this further to:
```
module.exports.webpack = function (webpackConfig) {
  webpackConfig.module.loaders.push({
    test   : /\.scss$/,
    loader : 'style!css!sass'
  });
  return webpackConfig;
};
```

Your example worked for me. All I did was create a `component-playground.config.js` file with the contents above and `npm install sass-loader` in the host project, and the playground was loading scss files successfully.

Can you provide more context and the errors webpack is throwing?

**Comment by ksmth** [comment]
Webpack doesn't throw any errors, so I suspect some kind of infinite loop going on. I'll have to dig into it, but I have no idea how to debug this.

**Comment by dmitry** [comment]
Looks like again https://github.com/jtangelder/sass-loader/issues/100 issue. Lets together fix this bug, because there are a lot of users stuck with it. Currently I'm on `sass-loader` v0.5.0, but it would be nice to be on the edge.

**Comment by eugene1g** [comment]
A long shot, but in try changing the shebang at https://github.com/skidding/cosmos/blob/master/bin/component-playground.js#L1 to `#!/usr/bin/env UV_THREADPOOL_SIZE=100 node`

(related report: https://github.com/jtangelder/sass-loader/issues/99#issuecomment-103281100)

**Comment by skidding** [comment]
@ksmth any update on this issue?

**Comment by skidding** [comment]
Cosmos is now a [boilerplate](https://github.com/skidding/cosmos/tree/master/webpack-boilerplate/react-0.13). You should be able to install any loaders you want now.
