### ISSUE TITLE
Support arbitrary component folder structure

### ISSUE THREAD

**Issue by lapanoid** [skidding/cosmos#138]
When project start to grow it became difficult to keep components in one folder, now to use cosmos I have to keep structure flat which is frustrating.

**Comment by skidding** [comment]
Why do you say the structure needs to be flat? You can nest the components with how many levels you want.

1. The a look at the file structure example in the README: https://github.com/skidding/cosmos#file-structure
2. The fixture path regexp supports nested components: https://github.com/skidding/cosmos/blob/master/component-playground/lib/parse-fixture-path.js#L3
3. Here is a test for nested component fixtures: https://github.com/skidding/cosmos/blob/master/tests/component-playground/lib/parse-fixture-path.js#L12-L17

Come to think of it, it's your PR that might break this. By the look of regexp in the parseComponentPath function it only supports one level of component hierarchy: https://github.com/lapanoid/cosmos/blob/master/component-playground/lib/parse-component-path.js#L3

**Comment by lapanoid** [comment]
My bad, it works fine. Need to read more carefully missed paragraph about file structure.
