### ISSUE TITLE
a range of errors

### ISSUE THREAD

**Issue by faassen** [skidding/cosmos#143]
I am having trouble getting cosmos to run reliably. Perhaps some of the dependencies have been updated and that causes trouble? Or perhaps I'm doing something wrong, in which case we can investigate what in Cosmos or its documentation can be improved to avoid this in the future.

First a usability issue. Initially I forgot to export the React component under test as the default of the module. I got some error about `type.toUpperCase` not being a function. It'd be nicer if this failure case was detected and the error can be more informative, i.e. failed to find component in module, or whatever.

When actually running the system, I am getting a few more errors. After initial load I get one of these:

```
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.
```

when I try to edit the fixture data in the browser window, I get a ton of these, I think one for every key press:

```
Uncaught Error: Invariant Violation: removeComponentAsRefFrom(...): Only a ReactOwner can have refs. This usually means that you're trying to remove a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.
```

probably due to the error the component doesn't update either.

When I edit the .jsx file with the component in it, I get the following message:

```
It appears that React Hot Loader isn't configured correctly. If you're using NPM, make sure your dependencies don't drag duplicate React distributions into their node_modules and that require("react") corresponds to the React instance you render your app with. If you're using a precompiled version of React, see https://github.com/gaearon/react-hot-loader/tree/master/docs#usage-with-external-react for integration instructions.
```

and the component UI does not update properly either. Only a full browser reload will reflect my edit.

**Comment by gaearon** [comment]
Can you check if you have multiple Reacts on one page? These errors definitely look like a “duplicate React” issue.

**Comment by faassen** [comment]
I'll add that I followed the Cosmos installation instructions on a clean package (though I did do a --save-dev for cosmos-js).

I was using npm 2.5.1. I just updated it to npm 2.13.0 to see whether this makes any difference. Unfortunately it does not. (I do get a ton of exciting warnings involving peerDependencies now during the npm run)

I tried installing without --save-dev, but this also has the same behavior.

So from my end it seems like installing cosmos as per instructions gives you these errors in a repeatable fashion.

**Comment by faassen** [comment]
I added issue #144 about cosmos not ignoring editor droppings. It's conceivable that this has something to do with these errors, though it seems unlikely, but I thought I'd mention it.

**Comment by faassen** [comment]
Is there an easy way to test whether there are multiple reacts included in a webpack?

**Comment by skidding** [comment]
> Can you check if you have multiple Reacts on one page? These errors definitely look like a “duplicate React” issue.

+1

> Is there an easy way to test whether there are multiple reacts included in a webpack?

Look for something unique from the React source in an unminified bundle and see if you find it twice or more. My quickest way to check is to see if the bundle is double the lines of code it usually is, because React is 99% of the bundle in a small project :)

> I'll add that I followed the Cosmos installation instructions on a clean package (though I did do a --save-dev for cosmos-js).

Can you open source that setup if you started from scratch? It would be easier for us to investigate this way.
