### ISSUE TITLE
Multiple components exported

### ISSUE THREAD

**Issue by oguzbilgic** [skidding/cosmos#145]
I'm not sure if I'm suppose to ask this here but..

How do write fixtures for modules that export multiple components?

**Comment by skidding** [comment]
Cosmos currently works with one component per module only. What you can do (though I'm not sure why you'd bundle more components into one module) is create your own Cosmos integration by working with the [ComponentPlayground](https://github.com/skidding/react-component-playground#react-component-playground) directly. You can parse your modules however you want and then construct the ComponentPlayground props manually.

**Comment by skidding** [comment]
You can now achieve this by customizing [get-component-fixture-tree.js](https://github.com/skidding/cosmos/blob/master/webpack-boilerplate/react-0.13/playground/get-component-fixture-tree.js). Check out the new docs: https://github.com/skidding/cosmos/tree/master/webpack-boilerplate/react-0.13
