### ISSUE TITLE
Uncaught Error: Invariant Violation: addComponentAsRefTo(...)

### ISSUE THREAD

**Issue by AddictArts** [skidding/cosmos#148]
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner

Just testing a simple component taken from the cosmos-example and I pulled out flux and the store leaving just the simple button.

**Comment by skidding** [comment]
> Just testing a simple component taken from the cosmos-example and I pulled out flux and the store leaving just the simple button.

Can you please describe the steps to reproduce this more accurately? I removed the Flux button along with the dispatcher and store and the other components worked just fine.

**Comment by AddictArts** [comment]
I setup a new folder with and starter with my own webpack config plus react, css-loader, etc. Then I created the folders src/components, etc. Then installed cosmos-js and copied the simple button component from the example. That is what I remember and unfortunately can't reproduce it. So, you can close this. Thanks

**Comment by skidding** [comment]
Thanks.

**Comment by gaearon** [comment]
This error means you had a duplicate React in the bundle, and different components were rendered with different versions.
