### ISSUE TITLE
Is it possible to have a config option for components say in a src directory along with the fixtures

### ISSUE THREAD

**Issue by AddictArts** [skidding/cosmos#149]
The component playground will not find the components and fixtures if they are not at the root of the project

**Comment by pekala** [comment]
As specified [in docs](https://github.com/skidding/cosmos#file-structure) you can use CLI options to point to correct directories: 

    node_modules/.bin/component-playground --components-path src/components --fixtures-path tests/fixtures

**Comment by AddictArts** [comment]
Thank you. I must have missed it
