### ISSUE TITLE
cosmos-js depends on react which could conflict with your node_modules/react

### ISSUE THREAD

**Issue by AddictArts** [skidding/cosmos#150]
The old solutions was peerDependency, but it seems a new install suggestion for react, react-hot-loader, etc

**Comment by skidding** [comment]
Why would it conflict? It's [only a peerDependency.](https://github.com/skidding/cosmos/blob/60bc9fa893b79cbb404e0b028916a4ec8aa09287/package.json#L45)

> but it seems a new install suggestion for react, react-hot-loader, etc

What do you mean by this?

**Comment by AddictArts** [comment]
Something after installing cosmos-js to an existing project installed a copy of react in its node_modules. That was what I got a conflict error on. Can't reproduce now though.

What I meant is that peerDependencies are going away, so should the install instructions be something like: npm install react react-hot-loader cosmos-js
instead of depending on the deprecated peerDependency of npm.

**Comment by AddictArts** [comment]
Thanks, you can close this since I can't reproduce.

**Comment by skidding** [comment]
Thanks for the heads-up, will have to read more about the peerDependency deprecation.

**Comment by pekala** [comment]
They are not getting deprecated altogether, it's just that they will not be automatically installed, see here http://blog.npmjs.org/post/110924823920/npm-weekly-5

**Comment by AddictArts** [comment]
Ah that was a good read on it, so it is nice the installer will be told the peer dependency did not install. Thanks

**Comment by skidding** [comment]
> They are not getting deprecated altogether, it's just that they will not be automatically installed,

That's good, it should be like this. React has a reputation for not working with more than one instance bundled together :)
