### ISSUE TITLE
props are undefined

### ISSUE THREAD

**Issue by joaomilho** [skidding/cosmos#152]
I'm trying cosmos and I'm having the following problem:

```
Uncaught TypeError: Cannot read property '...' of undefined
```

Where "..." is always one of the props of the components I'm trying to render (I've tried a couple).

Some info:

1) I'm using components with the es6 syntax.
2) cosmos-js: ^0.6.6

```
✗ node -v
v0.10.36

✗ npm ls react
ui-components@0.0.1 /Users/jm/p/ui-components
└── react@0.13.3
```

**Comment by joaomilho** [comment]
Apparently this is caused by using es6's `get`. Yo can try with:

```
import React from 'react';

export default class C extends React.Component {
  get a() {
     return "get is the problem";
  }

  render() {
    return (<div>{ this.a }</div>);
  }
}
```

When I compile this component to es5, I get the problem above. If I change it to the following it works fine.

```
import React from 'react';

export default class C extends React.Component {
  a() {
     return "get is the problem";
  }

  render() {
    return (<div>{ this.a() }</div>);
  }
}
```

Therefore, I think it's a bug and should be fixed, since I don't wanna remove the [cool] gets in my code. WDYT?

**Comment by skidding** [comment]
I tried adding a getter to the http://github.com/skidding/cosmos-example repo to see if your error reproduces. Indeed, it crashes:

```
Uncaught TypeError: Cannot set property a of #<SimpleButton> which has only a getter
```

But if I'm not mistaken, it's triggered by https://github.com/gaearon/react-hot-loader. See https://github.com/gaearon/react-hot-loader/issues/131

1. One quick fix is to create a corresponding setter, but it might still have side effects.
2. Until the issue gets fixed, you can use a react-hot-loader fork. You can follow instructions [here](https://github.com/gaearon/react-hot-api/pull/16#issuecomment-128419349) and then install `cosmos-js` again in your project. It worked for me.

**Comment by gaearon** [comment]
We're going to support getters real soon, I promise.
Give us a few more days.

**Comment by joaomilho** [comment]
:+1:

**Comment by skidding** [comment]
Cosmos no longer uses `react-hot-loader`. It now extends `react-transform-boilerplate`. Check out the new docs: https://github.com/skidding/cosmos/tree/master/webpack-boilerplate/react-0.13
