### ISSUE TITLE
Is forceUpdate needed or other issue with react-render-visualizer

### ISSUE THREAD

**Issue by AddictArts** [skidding/cosmos#153]
I had a component that used react-render-visualizer as a mixin. I noticed the updated render happening and was wondering if that is by design or intentional? If it is it might be nice to somehow work with react-render-visualizer. Thanks
<img width="644" alt="forceupdate" src="https://cloud.githubusercontent.com/assets/911906/9346274/c61a3d04-45cf-11e5-8c99-4704a9a92a94.png">

**Comment by skidding** [comment]
- Does the rendering happen continuously without doing anything with the component? If so, how often?
- Does this happen for any component? Including ones from the `cosmos-example` repo?

I didn't have time to test react-render-visualizer, but ComponentPlayground shouldn't re-render unless
1. the component re-renders by itself
2. you change the fixture in the editor

Here's a gif I made that confirms this:
![no-rerender](https://cloud.githubusercontent.com/assets/250750/9561834/f2dc80fc-4e5f-11e5-9f5f-ebc700687a9d.gif)

**Comment by skidding** [comment]
@AddictArts let me know if you have more data on this topic.
