### ISSUE TITLE
Cannot run `css-loader?modules`

### ISSUE THREAD

**Issue by bbirand** [skidding/cosmos#155]
I am trying to migrate a site to using CSS within components. One of the major reasons for doing so it so be able to use cosmos. The way I approach this problem is to first import the styles within the component:

```javascript
import styles from './bootstrap-layout.css';
```

Then use the style as the `className`:
```javascript
<div className={styles['col-xs-12']}>...</div>
```

I have the following in my `loaders` for `webpack`:
```
{test: /\.css$/, loader: "style-loader!css-loader?modules"}
```

This all works in regular `webpack`. I am trying to achieve the same using `cosmos`.

I added the following to the `component-playground.config.js` file:

```
module.exports.webpack = function(config) {
  config.module.loaders[1]= {
      test: /\.css$/,
      loader: 'style-loader!css-loader?modules'
    };
  return config;
};
```

But the imported `styles` object still remains `undefined`.

Any idea how to achieve this?  `Cosmos` seems to be the perfect use case for css-modules.

**Comment by fabiobiondi** [comment]
I have a similar problem.
I need to override the default CSS/LESS loaders to pass some parameters :

i.e. 
```
{
  test: /\.less/,
  loader: 'style!css-loader?module&localIdentName=less_[name]__[local]___[hash:base64:5]!less'
}
```

I have used a different approach by @bbirand  and I have completely overwritten the "loaders" property.
Anyway it works fine but although my custom loaders are used to load my css/less files, the parameters seem to be ignored and my CSS/LESS don't work as I would.

```
config.module.loaders = [
.,.. my loaders ...
]
return config;
```

Thanks in advance for your support.
Anyway, great work guys! I'm starting to love it!
