### ISSUE TITLE
Using bootstrap in conjunction with Cosmos

### ISSUE THREAD

**Issue by bbirand** [skidding/cosmos#157]
I styled most of my CSS inline using Radium. However, some of my components rely on Bootstrap (which is included via a `link` tag in my templates).

There is a line in the README about including external Javascript and CSS files:
```javascript
config.entry.push(path.join(process.cwd(), 'injectBootstrapTags.js'));
```

What is this `injectBootstrapTags.js` file? I basically only need to add `bootstrap.css` to the main page. How would I go about this?

Thanks!

**Comment by pekala** [comment]
In that file just inject the script/style tags from JS, for example like so:

    var script = document.createElement('script');
    script.setAttribute('src', '<filepath>.js');
    document.body.appendChild(script);

    var link = document.createElement('link');
    link.type = 'text/css';
    link.rel = 'stylesheet';
    link.href = '<filepath>.css';
    document.head.appendChild(link);

This file will be added to the bundle. You might want to use `unshift` instead of `push` to make sure that the file gets at the beginning of the bundle.

**Comment by bbirand** [comment]
Brilliant, thank you so much for the answer!

Also, as another quick question, what folder does webpack server look for files? In your example, where should I place `<filepath>.css`?

I added the CDN for bootstrap, but I have some other files I'd like to add.

**Comment by pekala** [comment]
It's looking in `process.cwd()` (current working directory)
