### ISSUE TITLE
Clicking an input 

### ISSUE THREAD

**Issue by ericclemmons** [skidding/cosmos#164]
```json
"cosmos-js": "0.6.8",
```

> ![click](https://cloud.githubusercontent.com/assets/15182/9894756/0fdce2c4-5bed-11e5-80fc-ddc03d5ef57d.gif)

My component optimistically set the internal state's value when clicked.  But, for some reason, `shouldComponentUpdate` is firing.

It looked like this should've been addressed in #133, but maybe it's something different?

Anyway, my main point is **this is still a really freaking awesome project!!!!**

**Comment by skidding** [comment]
> Anyway, my main point is this is still a really freaking awesome project!!!!

Thanks! A lot of work has been put into it but in a way it's just the beginning of what it can become :)

> My component optimistically set the internal state's value when clicked. But, for some reason, shouldComponentUpdate is firing.

I would need to see the source of that component. The component should not re-render unless you change the fixture or the fixture contents in the editor.

**Comment by skidding** [comment]
@ericclemmons is this still a problem?

**Comment by ericclemmons** [comment]
You know what, I honestly don't know.  The components got rewritten & now not seeing it.

:shrug:
