### ISSUE TITLE
Use React Transform instead of React Hot Loader

### ISSUE THREAD

**Issue by gaearon** [skidding/cosmos#165]
[React Transform](https://github.com/gaearon/babel-plugin-react-transform) is a Babel plugin for applying runtime transformations to React classes. Combined with [react-transform-webpack-hmr](https://github.com/gaearon/react-transform-webpack-hmr), it replaces React Hot Loader completely.

* [react-transform-boilerplate](https://github.com/gaearon/react-transform-boilerplate/)
* [example of porting react-hot-loader project to react-transform](https://github.com/gaearon/flux-react-router-example/commit/53e5ad5ec10974d195b002a3a07a3239d1478b7b)

Benefits:

* No need to have a dependency on `react/lib/ReactMount`
* Does not depend on `react` package: e.g. you can give it `react-native` in configuration just fine
* Better works with ES6 features like getters, and is much more stable
* Allows other transformations, e.g. [react-transform-catch-errors](https://github.com/gaearon/react-transform-catch-errors)

**Comment by skidding** [comment]
Almost managed to make it work.

The only incompatibility is that Babel looks for plugins in the current directory, while the entire Cosmos setup is made to [look for plugins inside the Cosmos package](https://github.com/skidding/cosmos/blob/master/component-playground/config.js#L50)

I wanted to make Cosmos work with as little setup as possible, but what it does with merging the user's webpack config with the one pre-packaged is most probably an anti-pattern and I've been meaning to change this for a while. Cosmos should give up trying to be a one-liner (`node_modules/.bin/component-playground`) and be turned into a boilerplate, like @gaearon's projects :). It's basically a setup of ComponentPlayground + Hot Reloading. It might be a bit less approachable at first but it would become more flexible, as a Browserify boilerplate would be almost just as easy to make as a webpack one. Currently it's tied to webpack.

**Comment by Dharmoslap** [comment]
+1

**Comment by Dharmoslap** [comment]
What is missing to get it working?

**Comment by skovhus** [comment]
Yes, what is missing?

**Comment by dmose** [comment]
+1

**Comment by skidding** [comment]
Done. Check out the new docs: https://github.com/skidding/cosmos/tree/master/webpack-boilerplate/react-0.13
