### ISSUE TITLE
Remove or update peerDependency React

### ISSUE THREAD

**Issue by oguzbilgic** [skidding/cosmos#166]
Currently `cosmos-js@0.6.8` doesn't install with `react@0.14.0-rc1`. So either remove or update the react peerDependency accordingly: `^0.14.0-rc1 || >= 0.13.0, < 0.15.0`

**Comment by eisisig** [comment]
+1

**Comment by skovhus** [comment]
+1

**Comment by skidding** [comment]
Cosmos is not yet up to speed with the new `ReactDOM` API. Did somebody test to see if the current version is still compatible with 0.14?

The change is pretty big and should come be made inside-out, starting with https://github.com/skidding/react-component-tree. Help is appreciated.

I wouldn't want to remove the peerDependency blindly and then have people complain Cosmos is broken on 0.14.

**Comment by goatslacker** [comment]
Just checked latest with React 0.14 and it seems to be working fine just spits out a few warnings.

**Comment by skidding** [comment]
> Just checked latest with React 0.14 and it seems to be working fine just spits out a few warnings.

Cosmos is now a [boilerplate](https://github.com/skidding/cosmos/tree/master/webpack-boilerplate/react-0.13), so you can now upgrade React to 0.14 in your project if everything already works well.

Will include a 0.14 boilerplate as well in the future.
