### ISSUE TITLE
Build code with cosmos

### ISSUE THREAD

**Issue by catalinmiron** [skidding/cosmos#168]
### Need

```gherkin
As a developer
I want to build my code using cosmos
So that I don't need an extra setup for bundling my code
And it will increase DX
```

### Deliverables

Cosmos will  bundle the code out of the box without headaches

**Comment by skidding** [comment]
How would you generate two HTML files and two .js bundles out of a single build task?

**Comment by eisisig** [comment]
I don't think it makes sense using cosmos webpack setup to bundle your personal components. You would have to config webpack for multiple entries and config all your 3rd party libs as externals so they won't get bundled with your components. And would you bundle/build ALL components or just once that have matching fixtures?

I think it's way easier to just add a babel script task and have cosmos and that run at the same time...

```
// to build
babel src --out-dir lib
// to watch
babel src --out-dir lib --watch
```

I often use https://www.npmjs.com/package/concurrently when I need to run multiple npm scripts at once...

**Comment by skidding** [comment]
Cosmos is now a [boilerplate](https://github.com/skidding/cosmos/tree/master/webpack-boilerplate/react-0.13) and the `devServer` works for both your dev environment and the playground, based on an `--env` var.
