### ISSUE TITLE
Only smart components?

### ISSUE THREAD

**Issue by satahippy** [skidding/cosmos#170]
Just a question. I can test only smart components (have a state) that way?

If my component don't have a state and depend on props, which come from the outside, i should test component, which pass that props. Right?

For example:

```js
class MyForm extends React.Component
{
	... 
	handleChange() {
		this.setState({checked: this.refs.checkbox.getDOMNode().checked});
	}
	
	render() {
		return (
			<MyCheckBox
				checked={this.state.checked}
				ref="checkbox"
				onChange={this.handleChange.bind(this)}
			/>
		);
	}
}
```

So i should test MyForm instead of MyCheckBox. Right?

**Comment by skidding** [comment]
Both. You can load any component in the playground as long as their props and/or state are serializable.

**Comment by satahippy** [comment]
here is fixture for MyCheckBox:
```js
export default {
	checked: false,
	onChange: ?
};
```
but the logic of onChange in the MyForm.
what should i do?

**Comment by skidding** [comment]
Well if you want to test the onChange handler you'll need to load the MyForm component in the playground. For the MyCheckBox component you can just do something like this:

```js
onChange: function() {
  console.log('Usually my parent deals with change'); // :)
}
``

**Comment by satahippy** [comment]
ok, thnx!
