### ISSUE TITLE
Unify 0.13 and 0.14 boilerplates

### ISSUE THREAD

**Issue by skidding** [skidding/cosmos#179]
By @goatslacker in #176 

> You can create a getDOMNode function like

> ```js
function getDOMNode(node) {
  return React.version.indexOf('0.14') > -1 ? node : node.getDOMNode();
}
```

> You can then also conditionally load ReactDOM and use it to render. That seems to be all you're using React 0.14 for.

> Also need to update the peer dependency requirements. You can probably even get away with 0.12 support.

**Comment by skidding** [comment]
> You can then also conditionally load ReactDOM and use it to render. That seems to be all you're using React 0.14 for.

@goatslacker Do you have any example for conditionally loading react-dom based on version?

I'm not sure what should go in the `peerDependencies` of the [smaller modules](https://github.com/skidding/cosmos/blob/master/CONTRIBUTING.md#packaging) that Cosmos is built on.

**Comment by goatslacker** [comment]
You wouldn't put reactdom in peer dependencies and just mention it in readme or something. 

ReactDom = React.version ? require('react-dom') : React
